services:
  mobile:
    build: .
    container_name: mobile
    ports:
      - 8081:8081 # Web preview
    volumes:
      - ./src:/usr/src/mobile
      - /usr/src/mobile/node_modules # Anonymous volume for modules
