version: '3.9'

services:
  api:
    build: ../api
    container_name: api 
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ../api:/code
    env_file:
      - ../api/.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend_dev
    working_dir: /app
    volumes:
      - ../frontend:/app        # Mount your frontend folder for live updates
      - /app/node_modules       # Anonymous volume to isolate node_modules from the host
    ports:
      - "5173:5173"             # Map Vite's dev server port to your host
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Improves file watching inside Docker
